### ISSUE TITLE
Build on Windows, cannot open include 'bogus/Extra'

### ISSUE THREAD

**Issue by rozentill** [lijieumn/argus-distribution#1]
Hi there,

Thanks for sharing the codes, actually I wonder if this can be built on Windows. I've tried and meet many problems, such as 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C1083	Cannot open include file: 'bogus/Extra/SecondOrder.fwd.hpp': No such file or directory	Argus-distribution_bogus	d:\project\argus-distribution\deps\bogus-interface\interface\src\MCPLaw.hh	4	
> 

It seems the folder 'Extra' is under "deps\bogus-interface\extern\so-bogus\src", so how can it be found by 'bogus\Extra', did I miss something or just define some variables?

Thanks,
Ryan

**Comment by narain** [comment]
Hi Ryan, unfortunately we haven't tested the code in Windows and have no plans to do so. If you find a solution, please share it with us.

**Comment by wxhaooo** [comment]
I compile Argus in windows 10 by Visual studio 2019 successfully. You need to compile Boost, GLEW, GLFW, libpng and zlib(which I use Anaconda). Next, you should promise the libraries and head file can be found by CMake(you can use environment variables and using set(XXX $ENV{XXX}))rather than FIND_PACKAGE(XXX) in windows). Finally, some errors related to complier should be attention.(For example, you could need to add Preprocessor _CRT_NO_VA_START_VALIDATION in arcsim project to avoid some error in VS )

**Comment by rozentill** [comment]
Thanks, I recently also compiled it successfully in VS 2017. We found that there are some codes need to be modified for Windows.
