### ISSUE TITLE
cannot load custom scene

### ISSUE THREAD

**Issue by liminchen** [lijieumn/argus-distribution#9]
I tried to design a scene with a stack of cloth dropped onto a ground, but I cannot load the scene successfully. I already compact all disconnected components into a single obj file (it seems multiple files does not work), and I had texture coordinates. But while loading I simply get `Segmentation fault (core dumped)`
Here are my scene files and meshes:
https://www.dropbox.com/s/jyb4p8evne8vtwk/clothStack.json?dl=0
https://www.dropbox.com/s/2w75n2griimtscx/clothStack_Ag.obj?dl=0
https://www.dropbox.com/s/a3h9m47jehyke9g/square21.obj?dl=0
when `relax_initial_state` is set `true` I can get `alglib::ap_error`, so I set it `false`.

**Comment by lijieumn** [comment]
Hi there, I just checked your clothStack_Ag.obj file and found it incompatible with the current implementation. In order to simulate a bunch of disconnected cloth in a single file, you need to avoid overlapping between their UV texture coordinates. The following picture shows the UV coordinates of your obj file.

![image](https://user-images.githubusercontent.com/25521849/96806161-ede4f180-13d8-11eb-9449-9ed1ef6d0045.png)

Following is the example where the texture coordinate works with the current code.

![image](https://user-images.githubusercontent.com/25521849/96806387-93986080-13d9-11eb-9402-2e4fa7535495.png)

Let me know if you have other issues.

**Comment by liminchen** [comment]
Thanks for your reply! It is actually my bad, there's isolated points in my mesh...
After removing the isolated points I can simulate it in Argus now with `relax_initial_state` set to `false`.
With default `relax_initial_state`, I get
`terminate called after throwing an instance of 'alglib::ap_error'`
But I guess it's fine for now if it does not affect the simulation.
